server:
  port: 8190
  servlet:
    context-path: /winter-market-carts
integrations:
  product-service:
    url: http://localhost:8189/winter-market-core/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000
cart-service:
  cart-prefix: winter_cart_